# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ...public.modeldb.metadata import MetadataService_pb2 as protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2


class MetadataServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getLabels = channel.unary_unary(
        '/ai.verta.modeldb.metadata.MetadataService/getLabels',
        request_serializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.GetLabels.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.GetLabels.Response.FromString,
        )
    self.addLabels = channel.unary_unary(
        '/ai.verta.modeldb.metadata.MetadataService/addLabels',
        request_serializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.AddLabels.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.AddLabels.Response.FromString,
        )
    self.deleteLabels = channel.unary_unary(
        '/ai.verta.modeldb.metadata.MetadataService/deleteLabels',
        request_serializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.DeleteLabels.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.DeleteLabels.Response.FromString,
        )


class MetadataServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getLabels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addLabels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteLabels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getLabels': grpc.unary_unary_rpc_method_handler(
          servicer.getLabels,
          request_deserializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.GetLabels.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.GetLabels.Response.SerializeToString,
      ),
      'addLabels': grpc.unary_unary_rpc_method_handler(
          servicer.addLabels,
          request_deserializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.AddLabels.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.AddLabels.Response.SerializeToString,
      ),
      'deleteLabels': grpc.unary_unary_rpc_method_handler(
          servicer.deleteLabels,
          request_deserializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.DeleteLabels.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_metadata_dot_MetadataService__pb2.DeleteLabels.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ai.verta.modeldb.metadata.MetadataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
