# THIS FILE IS AUTO-GENERATED. DO NOT EDIT

from enum import Enum

class ModelResourceEnumModelDBServiceResourceTypes(Enum):
  UNKNOWN = "UNKNOWN"
  ALL = "ALL"
  PROJECT = "PROJECT"
  EXPERIMENT = "EXPERIMENT"
  EXPERIMENT_RUN = "EXPERIMENT_RUN"
  DATASET = "DATASET"
  DATASET_VERSION = "DATASET_VERSION"
  DASHBOARD = "DASHBOARD"
