# THIS FILE IS AUTO-GENERATED. DO NOT EDIT

from enum import Enum

class IDTypeEnumIDType(Enum):
  UNKNOWN = "UNKNOWN"
  VERSIONING_REPOSITORY = "VERSIONING_REPOSITORY"
  VERSIONING_COMMIT = "VERSIONING_COMMIT"
