# THIS FILE IS AUTO-GENERATED. DO NOT EDIT

from enum import Enum

class PathLocationTypeEnumPathLocationType(Enum):
  LOCAL_FILE_SYSTEM = "LOCAL_FILE_SYSTEM"
  NETWORK_FILE_SYSTEM = "NETWORK_FILE_SYSTEM"
  HADOOP_FILE_SYSTEM = "HADOOP_FILE_SYSTEM"
  S3_FILE_SYSTEM = "S3_FILE_SYSTEM"
