# THIS FILE IS AUTO-GENERATED. DO NOT EDIT

from enum import Enum

class ServiceEnumService(Enum):
  UNKNOWN = "UNKNOWN"
  ALL = "ALL"
  ROLE_SERVICE = "ROLE_SERVICE"
  AUTHZ_SERVICE = "AUTHZ_SERVICE"
  MODELDB_SERVICE = "MODELDB_SERVICE"
