# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/public/modeldb/versioning/Environment.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/public/modeldb/versioning/Environment.proto',
  package='ai.verta.modeldb.versioning',
  syntax='proto3',
  serialized_options=b'P\001ZIgithub.com/VertaAI/modeldb/protos/gen/go/protos/public/modeldb/versioning',
  serialized_pb=b'\n2protos/public/modeldb/versioning/Environment.proto\x12\x1b\x61i.verta.modeldb.versioning\"\x94\x02\n\x0f\x45nvironmentBlob\x12\x44\n\x06python\x18\x01 \x01(\x0b\x32\x32.ai.verta.modeldb.versioning.PythonEnvironmentBlobH\x00\x12\x44\n\x06\x64ocker\x18\x02 \x01(\x0b\x32\x32.ai.verta.modeldb.versioning.DockerEnvironmentBlobH\x00\x12T\n\x15\x65nvironment_variables\x18\x03 \x03(\x0b\x32\x35.ai.verta.modeldb.versioning.EnvironmentVariablesBlob\x12\x14\n\x0c\x63ommand_line\x18\x04 \x03(\tB\t\n\x07\x63ontent\"7\n\x18\x45nvironmentVariablesBlob\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"E\n\x16VersionEnvironmentBlob\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05patch\x18\x03 \x01(\x05\"\x8d\x01\n PythonRequirementEnvironmentBlob\x12\x0f\n\x07library\x18\x01 \x01(\t\x12\x12\n\nconstraint\x18\x02 \x01(\t\x12\x44\n\x07version\x18\x03 \x01(\x0b\x32\x33.ai.verta.modeldb.versioning.VersionEnvironmentBlob\"\x86\x02\n\x15PythonEnvironmentBlob\x12\x44\n\x07version\x18\x01 \x01(\x0b\x32\x33.ai.verta.modeldb.versioning.VersionEnvironmentBlob\x12S\n\x0crequirements\x18\x02 \x03(\x0b\x32=.ai.verta.modeldb.versioning.PythonRequirementEnvironmentBlob\x12R\n\x0b\x63onstraints\x18\x03 \x03(\x0b\x32=.ai.verta.modeldb.versioning.PythonRequirementEnvironmentBlob\"E\n\x15\x44ockerEnvironmentBlob\x12\x12\n\nrepository\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0b\n\x03sha\x18\x03 \x01(\tBMP\x01ZIgithub.com/VertaAI/modeldb/protos/gen/go/protos/public/modeldb/versioningb\x06proto3'
)




_ENVIRONMENTBLOB = _descriptor.Descriptor(
  name='EnvironmentBlob',
  full_name='ai.verta.modeldb.versioning.EnvironmentBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='python', full_name='ai.verta.modeldb.versioning.EnvironmentBlob.python', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='docker', full_name='ai.verta.modeldb.versioning.EnvironmentBlob.docker', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='environment_variables', full_name='ai.verta.modeldb.versioning.EnvironmentBlob.environment_variables', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command_line', full_name='ai.verta.modeldb.versioning.EnvironmentBlob.command_line', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='ai.verta.modeldb.versioning.EnvironmentBlob.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=84,
  serialized_end=360,
)


_ENVIRONMENTVARIABLESBLOB = _descriptor.Descriptor(
  name='EnvironmentVariablesBlob',
  full_name='ai.verta.modeldb.versioning.EnvironmentVariablesBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai.verta.modeldb.versioning.EnvironmentVariablesBlob.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ai.verta.modeldb.versioning.EnvironmentVariablesBlob.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=417,
)


_VERSIONENVIRONMENTBLOB = _descriptor.Descriptor(
  name='VersionEnvironmentBlob',
  full_name='ai.verta.modeldb.versioning.VersionEnvironmentBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='ai.verta.modeldb.versioning.VersionEnvironmentBlob.major', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='ai.verta.modeldb.versioning.VersionEnvironmentBlob.minor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patch', full_name='ai.verta.modeldb.versioning.VersionEnvironmentBlob.patch', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=488,
)


_PYTHONREQUIREMENTENVIRONMENTBLOB = _descriptor.Descriptor(
  name='PythonRequirementEnvironmentBlob',
  full_name='ai.verta.modeldb.versioning.PythonRequirementEnvironmentBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='library', full_name='ai.verta.modeldb.versioning.PythonRequirementEnvironmentBlob.library', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='constraint', full_name='ai.verta.modeldb.versioning.PythonRequirementEnvironmentBlob.constraint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='ai.verta.modeldb.versioning.PythonRequirementEnvironmentBlob.version', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=632,
)


_PYTHONENVIRONMENTBLOB = _descriptor.Descriptor(
  name='PythonEnvironmentBlob',
  full_name='ai.verta.modeldb.versioning.PythonEnvironmentBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ai.verta.modeldb.versioning.PythonEnvironmentBlob.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requirements', full_name='ai.verta.modeldb.versioning.PythonEnvironmentBlob.requirements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='constraints', full_name='ai.verta.modeldb.versioning.PythonEnvironmentBlob.constraints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=897,
)


_DOCKERENVIRONMENTBLOB = _descriptor.Descriptor(
  name='DockerEnvironmentBlob',
  full_name='ai.verta.modeldb.versioning.DockerEnvironmentBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repository', full_name='ai.verta.modeldb.versioning.DockerEnvironmentBlob.repository', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='ai.verta.modeldb.versioning.DockerEnvironmentBlob.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sha', full_name='ai.verta.modeldb.versioning.DockerEnvironmentBlob.sha', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=899,
  serialized_end=968,
)

_ENVIRONMENTBLOB.fields_by_name['python'].message_type = _PYTHONENVIRONMENTBLOB
_ENVIRONMENTBLOB.fields_by_name['docker'].message_type = _DOCKERENVIRONMENTBLOB
_ENVIRONMENTBLOB.fields_by_name['environment_variables'].message_type = _ENVIRONMENTVARIABLESBLOB
_ENVIRONMENTBLOB.oneofs_by_name['content'].fields.append(
  _ENVIRONMENTBLOB.fields_by_name['python'])
_ENVIRONMENTBLOB.fields_by_name['python'].containing_oneof = _ENVIRONMENTBLOB.oneofs_by_name['content']
_ENVIRONMENTBLOB.oneofs_by_name['content'].fields.append(
  _ENVIRONMENTBLOB.fields_by_name['docker'])
_ENVIRONMENTBLOB.fields_by_name['docker'].containing_oneof = _ENVIRONMENTBLOB.oneofs_by_name['content']
_PYTHONREQUIREMENTENVIRONMENTBLOB.fields_by_name['version'].message_type = _VERSIONENVIRONMENTBLOB
_PYTHONENVIRONMENTBLOB.fields_by_name['version'].message_type = _VERSIONENVIRONMENTBLOB
_PYTHONENVIRONMENTBLOB.fields_by_name['requirements'].message_type = _PYTHONREQUIREMENTENVIRONMENTBLOB
_PYTHONENVIRONMENTBLOB.fields_by_name['constraints'].message_type = _PYTHONREQUIREMENTENVIRONMENTBLOB
DESCRIPTOR.message_types_by_name['EnvironmentBlob'] = _ENVIRONMENTBLOB
DESCRIPTOR.message_types_by_name['EnvironmentVariablesBlob'] = _ENVIRONMENTVARIABLESBLOB
DESCRIPTOR.message_types_by_name['VersionEnvironmentBlob'] = _VERSIONENVIRONMENTBLOB
DESCRIPTOR.message_types_by_name['PythonRequirementEnvironmentBlob'] = _PYTHONREQUIREMENTENVIRONMENTBLOB
DESCRIPTOR.message_types_by_name['PythonEnvironmentBlob'] = _PYTHONENVIRONMENTBLOB
DESCRIPTOR.message_types_by_name['DockerEnvironmentBlob'] = _DOCKERENVIRONMENTBLOB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvironmentBlob = _reflection.GeneratedProtocolMessageType('EnvironmentBlob', (_message.Message,), {
  'DESCRIPTOR' : _ENVIRONMENTBLOB,
  '__module__' : 'protos.public.modeldb.versioning.Environment_pb2'
  # @@protoc_insertion_point(class_scope:ai.verta.modeldb.versioning.EnvironmentBlob)
  })
_sym_db.RegisterMessage(EnvironmentBlob)

EnvironmentVariablesBlob = _reflection.GeneratedProtocolMessageType('EnvironmentVariablesBlob', (_message.Message,), {
  'DESCRIPTOR' : _ENVIRONMENTVARIABLESBLOB,
  '__module__' : 'protos.public.modeldb.versioning.Environment_pb2'
  # @@protoc_insertion_point(class_scope:ai.verta.modeldb.versioning.EnvironmentVariablesBlob)
  })
_sym_db.RegisterMessage(EnvironmentVariablesBlob)

VersionEnvironmentBlob = _reflection.GeneratedProtocolMessageType('VersionEnvironmentBlob', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONENVIRONMENTBLOB,
  '__module__' : 'protos.public.modeldb.versioning.Environment_pb2'
  # @@protoc_insertion_point(class_scope:ai.verta.modeldb.versioning.VersionEnvironmentBlob)
  })
_sym_db.RegisterMessage(VersionEnvironmentBlob)

PythonRequirementEnvironmentBlob = _reflection.GeneratedProtocolMessageType('PythonRequirementEnvironmentBlob', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONREQUIREMENTENVIRONMENTBLOB,
  '__module__' : 'protos.public.modeldb.versioning.Environment_pb2'
  # @@protoc_insertion_point(class_scope:ai.verta.modeldb.versioning.PythonRequirementEnvironmentBlob)
  })
_sym_db.RegisterMessage(PythonRequirementEnvironmentBlob)

PythonEnvironmentBlob = _reflection.GeneratedProtocolMessageType('PythonEnvironmentBlob', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONENVIRONMENTBLOB,
  '__module__' : 'protos.public.modeldb.versioning.Environment_pb2'
  # @@protoc_insertion_point(class_scope:ai.verta.modeldb.versioning.PythonEnvironmentBlob)
  })
_sym_db.RegisterMessage(PythonEnvironmentBlob)

DockerEnvironmentBlob = _reflection.GeneratedProtocolMessageType('DockerEnvironmentBlob', (_message.Message,), {
  'DESCRIPTOR' : _DOCKERENVIRONMENTBLOB,
  '__module__' : 'protos.public.modeldb.versioning.Environment_pb2'
  # @@protoc_insertion_point(class_scope:ai.verta.modeldb.versioning.DockerEnvironmentBlob)
  })
_sym_db.RegisterMessage(DockerEnvironmentBlob)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
