# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ...public.modeldb.versioning import VersioningService_pb2 as protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2


class VersioningServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getRepository = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/getRepository',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepository.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepository.Response.FromString,
        )
    self.setRepository = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/setRepository',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetRepository.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetRepository.Response.FromString,
        )
    self.deleteRepository = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/deleteRepository',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteRepository.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteRepository.Response.FromString,
        )
    self.commitRepositoryBlobs = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/commitRepositoryBlobs',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.CommitRepositoryBlobs.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.CommitRepositoryBlobs.Response.FromString,
        )
    self.getRepositoryBlobs = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/getRepositoryBlobs',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryBlobs.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryBlobs.Response.FromString,
        )
    self.batchGetEntity = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/batchGetEntity',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.BatchGetEntity.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.BatchGetEntity.Response.FromString,
        )
    self.addEntity = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/addEntity',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.AddEntity.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.AddEntity.Response.FromString,
        )
    self.deleteEntity = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/deleteEntity',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteEntity.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteEntity.Response.FromString,
        )
    self.getRepositoryDiff = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/getRepositoryDiff',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryDiff.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryDiff.Response.FromString,
        )
    self.getRepositoryLog = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/getRepositoryLog',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryLog.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryLog.Response.FromString,
        )
    self.setTag = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/setTag',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetTag.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetTag.Response.FromString,
        )
    self.getTag = channel.unary_unary(
        '/ai.verta.modeldb.versioning.VersioningService/getTag',
        request_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetTag.SerializeToString,
        response_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetTag.Response.FromString,
        )


class VersioningServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getRepository(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setRepository(self, request, context):
    """If ID is missing, consider a new entry
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteRepository(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def commitRepositoryBlobs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRepositoryBlobs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def batchGetEntity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addEntity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteEntity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRepositoryDiff(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRepositoryLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setTag(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTag(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VersioningServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getRepository': grpc.unary_unary_rpc_method_handler(
          servicer.getRepository,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepository.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepository.Response.SerializeToString,
      ),
      'setRepository': grpc.unary_unary_rpc_method_handler(
          servicer.setRepository,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetRepository.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetRepository.Response.SerializeToString,
      ),
      'deleteRepository': grpc.unary_unary_rpc_method_handler(
          servicer.deleteRepository,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteRepository.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteRepository.Response.SerializeToString,
      ),
      'commitRepositoryBlobs': grpc.unary_unary_rpc_method_handler(
          servicer.commitRepositoryBlobs,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.CommitRepositoryBlobs.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.CommitRepositoryBlobs.Response.SerializeToString,
      ),
      'getRepositoryBlobs': grpc.unary_unary_rpc_method_handler(
          servicer.getRepositoryBlobs,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryBlobs.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryBlobs.Response.SerializeToString,
      ),
      'batchGetEntity': grpc.unary_unary_rpc_method_handler(
          servicer.batchGetEntity,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.BatchGetEntity.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.BatchGetEntity.Response.SerializeToString,
      ),
      'addEntity': grpc.unary_unary_rpc_method_handler(
          servicer.addEntity,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.AddEntity.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.AddEntity.Response.SerializeToString,
      ),
      'deleteEntity': grpc.unary_unary_rpc_method_handler(
          servicer.deleteEntity,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteEntity.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.DeleteEntity.Response.SerializeToString,
      ),
      'getRepositoryDiff': grpc.unary_unary_rpc_method_handler(
          servicer.getRepositoryDiff,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryDiff.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryDiff.Response.SerializeToString,
      ),
      'getRepositoryLog': grpc.unary_unary_rpc_method_handler(
          servicer.getRepositoryLog,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryLog.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetRepositoryLog.Response.SerializeToString,
      ),
      'setTag': grpc.unary_unary_rpc_method_handler(
          servicer.setTag,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetTag.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.SetTag.Response.SerializeToString,
      ),
      'getTag': grpc.unary_unary_rpc_method_handler(
          servicer.getTag,
          request_deserializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetTag.FromString,
          response_serializer=protos_dot_public_dot_modeldb_dot_versioning_dot_VersioningService__pb2.GetTag.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ai.verta.modeldb.versioning.VersioningService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
